name = "cluster-sync"
title = "MongoDB Cluster-to-Cluster Synchronization"

intersphinx = [ "https://docs.mongodb.com/manual/objects.inv" ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

[constants]
# constant = "value"
version = "1.0.0"

